#!/usr/bin/env python

# Try to clean up any tables that exist after the tests have run.

import boto3
import itertools
dynamodb = boto3.client("dynamodb", region_name="us-west-2")

# `it` follows continuation tokens,
# `tables` extracts "TableNames"
# `tables` flattens lists
it = dynamodb.get_paginator("list_tables").paginate()
tables = [response["TableNames"] for response in it]
tables = itertools.chain(*tables)

print("Cleaning up tables")
for table in tables:
    try:
        dynamodb.delete_table(TableName=table)
    except Exception:
        print("Failed to clean up table '{}'".format(table))
